### ISSUE TITLE
Unable to start test system 'slim': fitnesse.slim.SlimError: Got invalid slim header from client. Read the following:

### ISSUE THREAD

**Issue by dineshs-freshdesk** [lvonk/example-fitnesse-ruby-slim#1] opened 2017-03-08 07:04 UTC
its work perfectly with fitnesse jar version you have provided.but i am getting above error when trying to use latest version of ruby i.e v20161106.

when i debug its giving me below error 
lib/rubyslim/socket_service.rb:19:in `initialize': Permission denied - bind(2) for nil port 1 (Errno::EACCES)

it will be great if you fix this issue

**Comment by AlexMooney** [comment] 2017-10-17 13:24
I ran into this too.  I believe the problem was caused by [this PR](https://github.com/unclebob/fitnesse/pull/977) in Fitnesse.  I was able to use the [release of Fitnesse prior to that PR](http://fitnesse.org/.FrontPage.FitNesseDevelopment.FitNesseRelease20160618) and it still worked.  The fix would have to be made in the [rubyslim gem](https://github.com/unclebob/rubyslim).

**Comment by lvonk** [comment] 2017-10-24 16:58
Hi I am not using FitNesse anymore, so I won't fix this. Sorry.

**Closed as completed by lvonk** 2017-10-24 16:58 UTC
